apiVersion: 1

datasources:
  - uid: prometheus
    name: Prometheus
    type: prometheus
    orgId: 1
    typeName: Prometheus
    access: proxy
    url: http://prometheus:9090
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: TRACE
      httpMethod: POST
    readOnly: false
    editable: true

  - uid: tempo
    orgId: 1
    name: Tempo
    type: tempo
    typeName: Tempo
    access: proxy
    url: http://tempo:3300
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      nodeGraph:
        enabled: true
      serviceGraph:
        enabled: true
      search:
        hide: false
      tracesToLogs:
        datasourceUid: loki
        filterBySpanID: false
        filterByTraceID: true
        mapTagNamesEnabled: false
        tags:
          - container
    readOnly: false
    editable: true


  - uid: loki
    orgId: 1
    name: Loki
    type: loki
    typeName: Loki
    access: proxy
    url: http://loki:3100
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          name: ID de Rastreamento
          matcherRegex: (?:TRACE)=(\w+)
          url: ${__value.raw}
    readOnly: false
    editable: true