receivers:
  otlp:
    protocols:
      grpc:
      http:

  prometheus:
    config:
      scrape_configs:
        - job_name: 'quarkus'
          static_configs:
            - targets:
                - 'host.docker.internal:8080'

processors:
  batch:

exporters:
  otlp/grafana:
    endpoint: 'tempo:4317'
    tls:
      insecure: true

  prometheusremotewrite:
    endpoint: 'prometheus:9090/api/v1/write'
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/grafana]
