FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10

ENV TZ=America/Sao_Paulo
WORKDIR /quarkus

RUN chown 1001 /quarkus \
    && chmod "g+rwX" /quarkus \
    && chown 1001:root /quarkus

COPY --chown=1001:root build/*-runner /quarkus/app

EXPOSE 8080
USER 1001

ENTRYPOINT ["./app", "-Dquarkus.http.host=0.0.0.0"]
