server:
  http_listen_port: 3300
  log_level: info

stream_over_http_enabled: true
target: all

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 'tempo:4317'

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 10m

metrics_generator:
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: 'prometheus:9090/api/v1/write'
        send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces
  processor:
    local_blocks:
      filter_server_spans: false
      flush_to_storage: true
    service_graphs:
      wait: 10s
      max_items: 10000
    span_metrics:
      filter_policies:
        - include:
            match_type: strict
            attributes:
              - key: kind
                value: SPAN_KIND_SERVER

storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/data

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]
      generate_native_histograms: both