server:
  http_listen_port: 3300
  log_level: info

positions:
  filename: /etc/promtail/positions.yml
  sync_period: 5s

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values:
              - logging=promtail
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container

    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<data>\d{2}/\d{2}/\d{4} \d{2}:\d{2}:\d{2})\s+(?P<level>\w+)\s+\[TRACE\]=(?P<traceId>\w*)\s+\[SPAN\]=(?P<spanId>\w*)\s+\[CLASS\]=\[(?P<class>[^\]]+)\]\s+\[THREAD\]=\((?P<thread>[^\)]+)\)\s+(?P<message>.*)$'